name: myapp9
description: Flutter Myapp9

version: 1.3.3+22
# 大色玩 <jiangdonglianggm@gmail.com>
homepage: https://dasewan.blog.csdn.net/

publish_to: 'none'

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 去除网页URL中的“#”(hash) https://flutter.cn/docs/development/ui/navigation/url-strategies
  url_strategy: 0.3.0
  # Localization https://github.com/dart-lang/intl
  intl: ^0.19.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.4.0
  # 网络库 https://github.com/cfug/dio
  dio: ^5.7.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.28.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0
  sp_util: 2.0.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars_flutter3: ^3.0.0 # flustars很久不维护，可以使用这个替代
  # Flutter 轮播图 https://github.com/mdddj/flutter_swiper_null_safety
  flutter_swiper_null_safety_flutter3: ^4.0.3   # flutter_swiper很久不维护，可以使用这个替代
  # 启动URL的插件（支持Web） https://github.com/flutter/packages/tree/main/packages/url_launcher
  url_launcher: 6.3.0
  # 图片选择插件 https://github.com/flutter/packages/tree/main/packages/image_picker
  image_picker: 1.1.2
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^3.1.1
  # WebView插件 https://github.com/flutter/packages/tree/main/packages/webview_flutter
  webview_flutter: 4.8.0
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.2.0
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^2.0.0
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.5
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.4.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^7.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.1.2
  # 扫码 https://github.com/juliuscanute/qr_code_scanner
  # App Shortcuts https://github.com/flutter/packages/tree/main/packages/quick_actions
  quick_actions: 1.0.7
  # 振动 https://github.com/benjamindean/flutter_vibration
  vibration: 2.0.0
  vibration_web: 1.6.8
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 11.1.1
  # 桌面应用调整窗口的大小和位置 https://github.com/leanflutter/window_manager
  window_manager: 0.4.0
  # 高德2D地图插件（支持Web） https://github.com/dasewan/flutter_2d_amap
  # demo 用到的库
  # 刮刮卡 https://github.com/vintage/scratcher
  # 动画效果 https://github.com/xvrh/lottie-flutter
  lottie: ^3.1.2
  win32: 5.5.3
  # 以下是新增的
  carousel_slider: ^5.0.0
  flutter_custom_carousel_slider: ^1.2.0
  text_scroll: ^0.2.0
  skeletonizer: ^1.4.2
  just_the_tooltip: ^0.0.12
  permission_handler: ^11.3.1
  appcheck: ^1.5.2
  sticky_headers: ^0.3.0+2
  timelines: ^0.1.0
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  connectivity_plus: ^6.1.0
  geolocator: ^13.0.2
  get_ip_address: ^0.0.7
  flutter_contacts: ^1.1.9+2
  livelyness_detection: ^0.0.1+5
  flutter_native_contact_picker: ^0.0.9
  android_id: ^0.4.0
  network_info_plus: ^6.1.1
  flutter_simple_country_picker: ^0.2.1
  advance_country_picker:
    git: git@gitee.com:dasewan/advance_country_picker_fork.git
  pinput: ^5.0.0
  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  currency_formatter: ^2.2.2
#  photo_manager: ^3.0.0-dev.2
  #  -liveness_detection_flutter_plugin:
  #    git: git@gitee.com:dasewan/liveness.git
  #  -platform_device_id: ^1.0.1
  #  -root_check: ^0.0.2+1
  #  -wifi_info_plugin_plus: ^2.0.2
  #  -fluttercontactpicker: ^4.7.0

# https://github.com/dasewan/myapp9/issues/187
dependency_overrides:
  scrollable_positioned_list: ^0.3.2


dev_dependencies:
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # 黄金测试
#  flutter_goldens:
#    sdk: flutter
  # 单元测试
  test: ^1.16.8

# For information on the generic Dart part of this file, see the
# following page: https:/w.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/login/
    - assets/images/home/
    - assets/images/index/
    - assets/images/verify/
    - assets/images/verify/swipper/
    - assets/images/shop/
    - assets/images/banks/
    - assets/images/merchant/
    - assets/images/liveness/
    - assets/images/verify/id/1.json
    - assets/images/verify/id/2.json
    - assets/images/verify/id/3.json
    - assets/lottie/scroll.json
    - assets/lottie/scroll2.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
